---
- name: Setup Docker, WireGuard VPN, and Cloudflare Dynamic DNS
  hosts: localhost
  become: true
  become_method: sudo

  vars:
    cloudflare_email: "{{ cloudflare_email }}"
    cloudflare_api_token: "{{ cloudflare_api_token }}"
    cloudflare_zone: "{{ cloudflare_zone }}"
    cloudflare_record: "{{ cloudflare_record }}"
    wireguard_port: 51820
    wireguard_config_dir: "/etc/wireguard"
    ansible_user: "{{ lookup('env', 'USER') | default('admin') }}"  # Default to 'admin' if undefined
    become_password: "{{ lookup('env', 'BECOME_PASS') }}"  # Use environment variable for sudo password

  tasks:
    - name: Update and upgrade the system
      import_tasks: tasks/update_system.yml

    - name: Install required packages
      import_tasks: tasks/install_prerequisites.yml

    - name: Install Docker
      import_tasks: tasks/install_docker.yml

    - name: Set up WireGuard
      import_tasks: tasks/setup_wireguard.yml

    - name: Update Cloudflare DNS
      import_tasks: tasks/update_cloudflare_dns.yml
      tags:
        - update_dns