---
- name: Setup Docker, WireGuard VPN, and Cloudflare Dynamic DNS
  hosts: localhost
  become: true
  become_method: sudo

  vars_files:
    - credentials.yml  # Load credentials from the encrypted vault

  vars:
    wireguard_port: 51820
    wireguard_config_dir: "/etc/wireguard"
    ansible_user: "{{ lookup('env', 'USER') | default('admin') }}"  # Default to 'admin' if undefined

  tasks:

    - name: Update and upgrade the system
      import_tasks: tasks/update_system.yml

    - name: Install and sets up fail2ban
      import_tasks: tasks/install_setup_fail2ban.yml

    - name: Install required packages
      import_tasks: tasks/install_prerequisites.yml

    - name: Install Docker
      import_tasks: tasks/install_docker.yml

    - name: Set up WireGuard
      import_tasks: tasks/setup_wireguard.yml

    - name: Update Cloudflare DNS
      import_tasks: tasks/update_cloudflare_dns.yml
      tags:
        - update_dns