---
- name: Setup Docker, WireGuard VPN, and Cloudflare Dynamic DNS
  hosts: localhost
  become: true

  vars:
    cloudflare_email: "{{ lookup('env', 'CF_EMAIL') }}"
    cloudflare_api_token: "{{ lookup('env', 'CF_API_TOKEN') }}"
    cloudflare_zone: "balexto.dk"
    cloudflare_record: "vpn.balexto.dk"
    wireguard_port: 51820

  tasks:
    # Install prerequisites for Docker
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    # Add Docker's official GPG key
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Set up the Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    # Install Docker CE
    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    # Install Docker Compose
    - name: Install Docker Compose
      apt:
        name: docker-compose-plugin
        state: present

    # Set up WireGuard VPN
    - name: Create WireGuard container
      docker_container:
        name: wireguard
        image: linuxserver/wireguard
        state: started
        restart_policy: always
        ports:
          - "{{ wireguard_port }}:51820/udp"
        env:
          PUID: 1000
          PGID: 1000
          TZ: "Etc/UTC"
          SERVERURL: "{{ cloudflare_record }}"
          SERVERPORT: "{{ wireguard_port }}"
          PEERS: 1
          PEERDNS: 1.1.1.1
          ALLOWEDIPS: 0.0.0.0/0

    # Set up Cloudflare Dynamic DNS
    - name: Update Cloudflare DNS record
      community.general.cloudflare_dns:
        zone: "{{ cloudflare_zone }}"
        record: "{{ cloudflare_record }}"
        type: A
        value: "{{ ansible_default_ipv4.address }}"
        ttl: 120
        proxied: yes
        api_token: "{{ cloudflare_api_token }}"

    # Enable automatic updates
    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present

    - name: Enable automatic updates
      command: dpkg-reconfigure --priority=low unattended-upgrades